# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LearnRxSwiftApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearnRxSwiftApp

  target 'LearnRxSwiftAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearnRxSwiftAppUITests' do
    # Pods for testing
  end

pod 'RxSwift'
pod 'RxCocoa'
end
